<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-10 at 17:54:34.
 */
include('../include/class.pdogsb.test.php');

class PdoGsbTest extends PHPUnit_Extensions_Database_TestCase {

    // only instantiate pdo once for test clean-up/fixture load
    static private $pdo = null;
    // only instantiate PHPUnit_Extensions_Database_DB_IDatabaseConnection once per test
    private $conn = null;

    final public function getConnection() {
        if ($this->conn === null) {
            if (self::$pdo == null) {
                self::$pdo = new PDO($GLOBALS['DB_DSN'], $GLOBALS['DB_USER'], $GLOBALS['DB_PASSWD']);
            }
            $this->conn = $this->createDefaultDBConnection(self::$pdo, $GLOBALS['DB_DBNAME']);
        }

        return $this->conn;
    }

    public function getDataSet() {
        return $this->createMySQLXMLDataSet('gsb_frais.xml');
    }

    public function getNombreEtat(){
    $this->assertEquals(5, $this->getConnection()->getRowCount('etat'));
    }
}
